Vagrant.configure(2) do |config|

  config.vm.box = "laravel/homestead"

  config.vm.network "private_network", ip: "192.168.50.16"

  config.vm.synced_folder "../dev_box", "/vagrant", :owner => 'vagrant', :group => 'www-data'
  config.vm.synced_folder "../html", "/var/www/html", :owner => 'vagrant', :group => 'www-data'
  config.vm.synced_folder "../log", "/var/www/log", :owner => 'vagrant', :group => 'www-data'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "./provision.sh"

end